export const AVERAGE_TX_DURATION_MS = 6000;
export const CANCEL_TRANSACTION_TOAST_DEFAULT_DURATION = 20000;
export const CANCEL_TRANSACTION_TOAST_ID = 'cancel-transaction-toast';
export const EXTRA_GAS_LIMIT_GUARDED_TX = 50_000;
export const GAS_LIMIT = 50_000;
export const GAS_PER_DATA_BYTE = 1_500;
export const GAS_PRICE = 1_000_000_000;
export const GAS_PRICE_MODIFIER = 0.01;
export const REFUNDED_GAS = 'refundedGas';
export const TRANSACTIONS_STATUS_DROP_INTERVAL_MS = 10 * 60 * 1000; // 10min
export const TRANSACTIONS_STATUS_POLLING_INTERVAL_MS = 90 * 1000; // 90sec
export const WALLET_SIGN_SESSION = 'signSession';
